// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscribtion struct {
	ID           int64              `json:"id"`
	ServiceName  string             `json:"service_name"`
	PriceInRuble int32              `json:"price_in_ruble"`
	IDUser       int32              `json:"id_user"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	EndDate      pgtype.Timestamptz `json:"end_date"`
}
