// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
)

const findProductByID = `-- name: FindProductByID :one
SELECT id, service_name, price_in_ruble, id_user, start_date, end_date FROM subscribtions WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Subscribtion, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Subscribtion
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.PriceInRuble,
		&i.IDUser,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listAll = `-- name: ListAll :many
SELECT id, service_name, price_in_ruble, id_user, start_date, end_date FROM subscribtions
`

func (q *Queries) ListAll(ctx context.Context) ([]Subscribtion, error) {
	rows, err := q.db.Query(ctx, listAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscribtion
	for rows.Next() {
		var i Subscribtion
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.PriceInRuble,
			&i.IDUser,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
