// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	FindProductByID(ctx context.Context, id int64) (Subscribtion, error)
	ListAll(ctx context.Context) ([]Subscribtion, error)
}

var _ Querier = (*Queries)(nil)
