services:
  postgres:
    image: postgres:16-alpine
    container_name: efm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: efm
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# services:
#   postgres:
#     image: postgres:16-alpine
#     environment:
#       POSTGRES_DB: taskservice
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d taskservice"]
#       interval: 5s
#       timeout: 5s
#       retries: 10
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./migrations/00001_create_subs.up.sql:/docker-entrypoint-initdb.d/00001_create_subs.sql:ro

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       HTTP_ADDR: :8080
#       DATABASE_DSN: postgres://postgres:postgres@postgres:5432/taskservice?sslmode=disable
#     ports:
#       - "8080:8080"
#     depends_on:
#       postgres:
#         condition: service_healthy

# volumes:
#   postgres_data:
